import Head from 'next/head'
import matter from "gray-matter"
import fs from "fs"
import { Container, Box, Text, Tag } from "@chakra-ui/react";
import Link from 'next/link';
import {Post, HomePageProps} from "../types/type";
import { getAllPostsData } from '../utils/getPostsData';

export default function Home(props: HomePageProps) {
  return (
    <div>
      <Head>
        <title>tosalab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h1>Tosa.dev</h1>
          <p>悪の科学者を目指すブログ</p>
          <p>人生の走馬灯の半分くらいPCの画面</p>
          <Box margin="auto" paddingBottom="10" marginTop="20">
            <h3>Tags</h3>
            {props.tags.map(tag => {
              return <Tag margin="1" key={tag}>{tag}</Tag>
            })}
          </Box>
          <h3>Posts</h3>
          {props.contents.map(item => {
              return <PostItem 
                  {...item}
                  key={"post-key-" + item.data.slug}
              />;
          })}
        </Container>

      </main>
      <footer>
      </footer>
    </div>
  )
}

function PostItem(props: Post) {
  return (
    <Box key={props.data.slug}>
      <Link href={"/posts/" + props.data.slug}>
        <Container padding="2">
          <Text color="gray.600">{props.data.date}</Text>
          <Text fontWeight="bold" _hover={{ color: "#1A0DAB"}}>{props.data.title}</Text>
          <Text>{props.data.description}</Text>
          {props.data.tags != null && props.data.tags.map(item => {
            return <Tag marginRight="1" key={item}>{item}</Tag>
          })}
        </Container>           
      </Link>
    </Box>
  );
}


export async function getStaticProps() {
  const path = "./posts/";
  const contents = getAllPostsData(path);
  contents.forEach(item => {
    console.log(item.data.slug)
  })
  const tagSet = contents
                .reduce((acc:Set<string> , val) => {
                  if (val.data.tags != null) {
                    const tags = val.data.tags as string[];
                    tags.forEach(item => acc.add(item));
                  };
                  return acc;
                }, new Set<string>())
  const tags = Array.from(tagSet);
  return {
      props: {
        contents,
        tags
      }
  }
}