import { HeadData } from "../types/type";
import Head from "next/head";

export function BaseHeader(data: HeadData) {
    return (
      <Head>
        <title>TosaLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.5.1/katex.min.css"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="description" content="とさの開発ブログ"/>
        <link rel="canonical" href="https://tosa.dev"/>
        <meta property="og:title" content={data.title}/>
        <meta property="og:type" content="blog"/>
        <meta property="og:url" content={data.url}/>
        <meta property="og:image" content={"https://tosa.dev/icon.jpeg"}/>
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@tosa_now" />
        <meta name="twitter:player" content="@tosa_now" />
        <meta property="og:site_name" content="tosa.dev"/>
        <meta property="og:description" content={data.description}/> 
      </Head>
    );
  }